### ISSUE TITLE
Repositori masih kosong.

### ISSUE THREAD

**Issue by wahyudierwin** [thariqizmp/Indonesian_language_Tweet_Multiclass_Classification_using_IndoBERT-LSTM#1]
Mohon untuk source code dari skripsi Anda langsung di-push ke sini.

**Comment by thariqizmp** [comment]
Mohon maaf Pak Erwin saya terlupa untuk push code dari skripsi saya. Untuk code nya sudah saya push ke main branch ya pak. Sekali lagi mohon maaf dan terima kasih.
https://github.com/thariqizmp/Indonesian_language_Tweet_Multiclass_Classification_using_IndoBERT-LSTM.git
